export type MatchStatus = 'scheduled' | 'live' | 'finished' | 'postponed' | 'cancelled';
export type PoolMemberRole = 'owner' | 'admin' | 'player';
export type PredictionVisibility = 'kickoff' | 'always' | 'never';
export type PoolSettings = { prediction_visibility?: PredictionVisibility; lock_minutes?: number; [key: string]: unknown };
export type Profile = {
  id: string;
  username: string;
  display_name: string | null;
  recovery_email: string | null;
  avatar_url: string | null;
  is_active: boolean;
  access_code_rotated_at: string | null;
  onboarding_completed_at: string | null;
  created_at: string;
};
export type Pool = { id: string; slug: string; name: string; settings_json: PoolSettings; created_at: string };
export type PoolMember = { pool_id: string; profile_id: string; role: PoolMemberRole; joined_at: string };
export type Prediction = { id: string; pool_id: string; match_id: string; profile_id: string; home_goals: number; away_goals: number; advancing_team: "home" | "away" | null; points_awarded: number | null; created_at: string; updated_at: string };
export type MatchMvpPrediction = { id: string; pool_id: string; match_id: string; profile_id: string; player_name: string; team_name: string; points_awarded: number | null; created_at: string; updated_at: string };
export type TournamentGeneralPredictionsRow = {
  pool_id: string;
  profile_id: string;
  champion_team: string | null;
  finalist_team_a: string | null;
  finalist_team_b: string | null;
  top_scorer_player_name: string | null;
  top_scorer_team_name: string | null;
  tournament_mvp_player_name: string | null;
  tournament_mvp_team_name: string | null;
  golden_glove_player_name: string | null;
  golden_glove_team_name: string | null;
  created_at: string;
  updated_at: string;
};
export type TournamentOfficialAwardsRow = {
  pool_id: string;
  champion_team: string | null;
  finalist_team_a: string | null;
  finalist_team_b: string | null;
  top_scorer_player_name: string | null;
  top_scorer_team_name: string | null;
  tournament_mvp_player_name: string | null;
  tournament_mvp_team_name: string | null;
  golden_glove_player_name: string | null;
  golden_glove_team_name: string | null;
  recorded_by: string | null;
  recorded_at: string;
  updated_at: string;
};
export type TournamentGeneralPredictionScoreRow = {
  pool_id: string;
  profile_id: string;
  champion_points: number;
  finalists_points: number;
  top_scorer_points: number;
  tournament_mvp_points: number;
  golden_glove_points: number;
  total_points: number;
  calculated_at: string;
};
export type PoolMemberScore = { pool_id: string; profile_id: string; matchday_id: string; match_points: number; exact_hits: number; sign_hits: number; cumulative_points: number; rank: number | null; updated_at: string };
export type { QuizStartSession as QuizStartPayload } from "@/lib/quiz/types";

