import type { LabQuestion, LabQuestionFormat } from "@/lib/quiz/lab/types";
import { isDerivedLabAssetUrl } from "@/lib/quiz/lab/generate-question.client";

export const AUTO_GENERATED_LAB_FORMATS = [
  "image_trivia",
  "guess_player_hair",
  "guess_player_eyes",
  "guess_player_silhouette",
] as const;

export type AutoGeneratedLabFormat = (typeof AUTO_GENERATED_LAB_FORMATS)[number];

export function isAutoGeneratedLabFormat(
  format: LabQuestionFormat
): format is AutoGeneratedLabFormat {
  return (AUTO_GENERATED_LAB_FORMATS as readonly string[]).includes(format);
}

export function questionNeedsAutoGeneration(question: LabQuestion): boolean {
  if (!isAutoGeneratedLabFormat(question.format)) return false;

  if (question.format === "image_trivia") {
    const imageUrl = question.imageUrl?.trim() ?? "";
    return !question.momentId || !imageUrl.startsWith("/images/quiz/historic/");
  }

  if (
    question.format === "guess_player_hair" ||
    question.format === "guess_player_eyes" ||
    question.format === "guess_player_silhouette"
  ) {
    const imageUrl = question.imageUrl?.trim() ?? "";
    return !question.momentId || !isDerivedLabAssetUrl(imageUrl);
  }

  return false;
}

export function canAutoGenerateLabFormat(format: LabQuestionFormat): boolean {
  return isAutoGeneratedLabFormat(format);
}
