import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { AUTO_GENERATED_LAB_FORMATS, type AutoGeneratedLabFormat } from "@/lib/quiz/lab/auto-formats";
import { materializeLabQuestionAssets } from "@/lib/quiz/lab/materialize-assets.server";
import { generateLabQuestion } from "@/lib/quiz/lab/generate-question.server";
import type { LabQuestion } from "@/lib/quiz/lab/types";
import { seedFromQuizDate } from "@/lib/quiz/rng";

const MANIFEST_DIR = join(process.cwd(), "data/quiz/lab-daily");

/** Orden fijo del borrador diario de imagen (4 preguntas). */
export const DAILY_LAB_QUESTION_FORMATS: readonly AutoGeneratedLabFormat[] =
  AUTO_GENERATED_LAB_FORMATS;

export type QuizLabDailyPack = {
  quizDate: string;
  generatedAt: string;
  momentIds: string[];
  questions: LabQuestion[];
};

export type PregenerateQuizLabDailyPackResult = {
  quizDate: string;
  skipped: boolean;
  pack: QuizLabDailyPack | null;
};

function manifestPath(quizDate: string): string {
  return join(MANIFEST_DIR, `${quizDate}.json`);
}

function formatSeedForSlot(quizDate: string, slot: number): number {
  const base = seedFromQuizDate(quizDate);
  return base + slot * 9973;
}

export async function readQuizLabDailyPack(
  quizDate: string
): Promise<QuizLabDailyPack | null> {
  try {
    const raw = await readFile(manifestPath(quizDate), "utf8");
    return JSON.parse(raw) as QuizLabDailyPack;
  } catch {
    return null;
  }
}

export async function writeQuizLabDailyPack(pack: QuizLabDailyPack): Promise<void> {
  await mkdir(MANIFEST_DIR, { recursive: true });
  await writeFile(manifestPath(pack.quizDate), JSON.stringify(pack, null, 2), "utf8");
}

export async function pregenerateQuizLabDailyPack(
  quizDate: string,
  options?: { force?: boolean }
): Promise<PregenerateQuizLabDailyPackResult> {
  if (!options?.force) {
    const existing = await readQuizLabDailyPack(quizDate);
    if (existing?.questions?.length) {
      return { quizDate, skipped: true, pack: existing };
    }
  }

  const excludeMomentIds: string[] = [];
  const questions: LabQuestion[] = [];

  for (let slot = 0; slot < DAILY_LAB_QUESTION_FORMATS.length; slot++) {
    const format = DAILY_LAB_QUESTION_FORMATS[slot];
    const generated = await generateLabQuestion({
      format,
      questionId: `daily-${quizDate}-${format}`,
      seed: formatSeedForSlot(quizDate, slot),
      excludeMomentIds,
      minDifficulty: "medium",
      force: true,
    });

    if (!generated) continue;

    const materialized = await materializeLabQuestionAssets(generated, { force: true });
    questions.push(materialized);

    const momentId = "momentId" in materialized ? materialized.momentId : null;
    if (momentId) excludeMomentIds.push(momentId);
  }

  const pack: QuizLabDailyPack = {
    quizDate,
    generatedAt: new Date().toISOString(),
    momentIds: excludeMomentIds,
    questions,
  };

  await writeQuizLabDailyPack(pack);

  return { quizDate, skipped: false, pack };
}

/** Resumen ligero para `quizzes.settings_json`. */
export function labDailyPackSettingsSummary(pack: QuizLabDailyPack) {
  return {
    quiz_date: pack.quizDate,
    generated_at: pack.generatedAt,
    moment_ids: pack.momentIds,
    question_count: pack.questions.length,
    formats: pack.questions.map((q) => q.format),
  };
}
