import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { type AutoGeneratedLabFormat } from "@/lib/quiz/lab/auto-formats";
import { momentToImageTriviaQuestion } from "@/lib/quiz/lab/from-moment";
import { momentToSilhouetteQuestion } from "@/lib/quiz/lab/from-player-moment";
import {
  pickImageTriviaMoment,
  pickSilhouetteSourceMoment,
  normalizePlayerKey,
} from "@/lib/quiz/lab/moment-picker";
import { hasMaterializedSilhouette } from "@/lib/quiz/lab/silhouette-lab-pool.server";
import type { LabQuestion } from "@/lib/quiz/lab/types";
import { getWorldCupMomentsCatalog } from "@/lib/quiz/world-cup-moments-catalog";
import { seedFromQuizDate } from "@/lib/quiz/rng";
import type {
  PregenerateQuizLabDailyPackResult,
  QuizLabDailyPack,
} from "@/lib/quiz/lab/daily-pack-types";

const MANIFEST_DIR = join(process.cwd(), "data/quiz/lab-daily");

const DAILY_LAB_QUESTION_FORMATS: readonly AutoGeneratedLabFormat[] = [
  "image_trivia",
  "guess_player_silhouette",
] as const;

function manifestPath(quizDate: string): string {
  return join(MANIFEST_DIR, `${quizDate}.json`);
}

function formatSeedForSlot(quizDate: string, slot: number): number {
  const base = seedFromQuizDate(quizDate);
  return base + slot * 9973;
}

function playerKeysFromMomentId(momentId: string | null | undefined): string[] {
  if (!momentId) return [];
  const moment = getWorldCupMomentsCatalog().moments.find((row) => row.id === momentId);
  if (!moment) return [];
  return moment.players.map(normalizePlayerKey);
}

async function readManifest(quizDate: string): Promise<QuizLabDailyPack | null> {
  try {
    const raw = await readFile(manifestPath(quizDate), "utf8");
    return JSON.parse(raw) as QuizLabDailyPack;
  } catch {
    return null;
  }
}

function generateLightLabQuestion(args: {
  format: AutoGeneratedLabFormat;
  quizDate: string;
  slot: number;
  excludeMomentIds: string[];
  excludePlayerKeys: string[];
}): LabQuestion | null {
  const questionId = `daily-${args.quizDate}-${args.format}`;
  const seed = formatSeedForSlot(args.quizDate, args.slot);
  const pickerOpts = {
    seed,
    excludeIds: args.excludeMomentIds,
    excludePlayerKeys: args.excludePlayerKeys,
    minDifficulty: "medium" as const,
  };

  if (args.format === "image_trivia") {
    const moment = pickImageTriviaMoment(pickerOpts);
    return moment ? momentToImageTriviaQuestion(moment, questionId) : null;
  }

  const moment = pickSilhouetteSourceMoment({ ...pickerOpts, minDifficulty: "easy" });
  if (!moment || !hasMaterializedSilhouette(moment.id)) return null;
  return momentToSilhouetteQuestion(moment, questionId);
}

/** Pack diario sin sharp (Vercel cron / serverless). */
export async function pregenerateQuizLabDailyPackLight(
  quizDate: string,
  options?: { force?: boolean }
): Promise<PregenerateQuizLabDailyPackResult> {
  if (!options?.force) {
    const existing = await readManifest(quizDate);
    if (existing?.questions?.length) {
      return { quizDate, skipped: true, pack: existing };
    }
  }

  const excludeMomentIds: string[] = [];
  const excludePlayerKeys: string[] = [];
  const questions: LabQuestion[] = [];

  for (let slot = 0; slot < DAILY_LAB_QUESTION_FORMATS.length; slot++) {
    const format = DAILY_LAB_QUESTION_FORMATS[slot];
    const generated = generateLightLabQuestion({
      format,
      quizDate,
      slot,
      excludeMomentIds,
      excludePlayerKeys,
    });
    if (!generated) continue;

    questions.push(generated);
    const momentId = "momentId" in generated ? generated.momentId : null;
    if (momentId) excludeMomentIds.push(momentId);
    for (const playerKey of playerKeysFromMomentId(momentId)) {
      if (!excludePlayerKeys.includes(playerKey)) {
        excludePlayerKeys.push(playerKey);
      }
    }
  }

  const pack: QuizLabDailyPack = {
    quizDate,
    generatedAt: new Date().toISOString(),
    momentIds: excludeMomentIds,
    questions,
  };

  return { quizDate, skipped: false, pack };
}
