import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { AUTO_GENERATED_LAB_FORMATS, type AutoGeneratedLabFormat } from "@/lib/quiz/lab/auto-formats";
import {
  getDerivedLabAssetBuffer,
  momentSourceAbsolutePath,
  persistDerivedAssetToDisk,
  persistedDerivedAssetPublicUrl,
} from "@/lib/quiz/lab/derive-images.server";
import { generateLabQuestion } from "@/lib/quiz/lab/generate-question.server";
import type { LabQuestion } from "@/lib/quiz/lab/types";
import {
  isLabPlayerCropQuestion,
  isLabPlayerSilhouetteQuestion,
} from "@/lib/quiz/lab/types";
import { seedFromQuizDate } from "@/lib/quiz/rng";
import { pickMomentById } from "@/lib/quiz/world-cup-moments";
import { getWorldCupMomentsCatalog } from "@/lib/quiz/world-cup-moments-catalog";
import { resolveMomentImageUrl } from "@/lib/quiz/world-cup-moments";

const MANIFEST_DIR = join(process.cwd(), "data/quiz/lab-daily");

/** Orden fijo del borrador diario de imagen (4 preguntas). */
export const DAILY_LAB_QUESTION_FORMATS: readonly AutoGeneratedLabFormat[] =
  AUTO_GENERATED_LAB_FORMATS;

export type QuizLabDailyPack = {
  quizDate: string;
  generatedAt: string;
  momentIds: string[];
  questions: LabQuestion[];
};

export type PregenerateQuizLabDailyPackResult = {
  quizDate: string;
  skipped: boolean;
  pack: QuizLabDailyPack | null;
};

function manifestPath(quizDate: string): string {
  return join(MANIFEST_DIR, `${quizDate}.json`);
}

function formatSeedForSlot(quizDate: string, slot: number): number {
  const base = seedFromQuizDate(quizDate);
  return base + slot * 9973;
}

function variantForQuestion(question: LabQuestion): "hair" | "eyes" | "silhouette" | null {
  if (question.format === "guess_player_hair") return "hair";
  if (question.format === "guess_player_eyes") return "eyes";
  if (question.format === "guess_player_silhouette") return "silhouette";
  return null;
}

async function materializeQuestion(question: LabQuestion): Promise<LabQuestion> {
  const variant = variantForQuestion(question);
  const momentId = "momentId" in question ? question.momentId : null;
  if (!variant || !momentId) return question;

  const catalog = getWorldCupMomentsCatalog();
  const moment = pickMomentById(catalog, momentId, { readyOnly: true });
  const historicPath = moment ? resolveMomentImageUrl(moment) : null;
  if (!moment || !historicPath) return question;

  const buffer = await getDerivedLabAssetBuffer(
    momentSourceAbsolutePath(historicPath),
    momentId,
    variant,
    {
      moment: variant === "silhouette" ? moment : undefined,
      force: true,
    }
  );

  await persistDerivedAssetToDisk(momentId, variant, buffer);
  const staticUrl = persistedDerivedAssetPublicUrl(momentId, variant);

  if (isLabPlayerCropQuestion(question) || isLabPlayerSilhouetteQuestion(question)) {
    return { ...question, imageUrl: staticUrl };
  }
  return question;
}

export async function readQuizLabDailyPack(
  quizDate: string
): Promise<QuizLabDailyPack | null> {
  try {
    const raw = await readFile(manifestPath(quizDate), "utf8");
    return JSON.parse(raw) as QuizLabDailyPack;
  } catch {
    return null;
  }
}

export async function writeQuizLabDailyPack(pack: QuizLabDailyPack): Promise<void> {
  await mkdir(MANIFEST_DIR, { recursive: true });
  await writeFile(manifestPath(pack.quizDate), JSON.stringify(pack, null, 2), "utf8");
}

export async function pregenerateQuizLabDailyPack(
  quizDate: string,
  options?: { force?: boolean }
): Promise<PregenerateQuizLabDailyPackResult> {
  if (!options?.force) {
    const existing = await readQuizLabDailyPack(quizDate);
    if (existing?.questions?.length) {
      return { quizDate, skipped: true, pack: existing };
    }
  }

  const excludeMomentIds: string[] = [];
  const questions: LabQuestion[] = [];

  for (let slot = 0; slot < DAILY_LAB_QUESTION_FORMATS.length; slot++) {
    const format = DAILY_LAB_QUESTION_FORMATS[slot];
    const generated = await generateLabQuestion({
      format,
      questionId: `daily-${quizDate}-${format}`,
      seed: formatSeedForSlot(quizDate, slot),
      excludeMomentIds,
      minDifficulty: "medium",
      force: true,
    });

    if (!generated) continue;

    const materialized = await materializeQuestion(generated);
    questions.push(materialized);

    const momentId = "momentId" in materialized ? materialized.momentId : null;
    if (momentId) excludeMomentIds.push(momentId);
  }

  const pack: QuizLabDailyPack = {
    quizDate,
    generatedAt: new Date().toISOString(),
    momentIds: excludeMomentIds,
    questions,
  };

  await writeQuizLabDailyPack(pack);

  return { quizDate, skipped: false, pack };
}

/** Resumen ligero para `quizzes.settings_json`. */
export function labDailyPackSettingsSummary(pack: QuizLabDailyPack) {
  return {
    quiz_date: pack.quizDate,
    generated_at: pack.generatedAt,
    moment_ids: pack.momentIds,
    question_count: pack.questions.length,
    formats: pack.questions.map((q) => q.format),
  };
}
