import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { type AutoGeneratedLabFormat } from "@/lib/quiz/lab/auto-formats";
import { materializeLabQuestionAssets } from "@/lib/quiz/lab/materialize-assets.server";
import { generateLabQuestion } from "@/lib/quiz/lab/generate-question.server";
import { normalizePlayerKey } from "@/lib/quiz/lab/moment-picker";
import type { LabQuestion } from "@/lib/quiz/lab/types";
import { getWorldCupMomentsCatalog } from "@/lib/quiz/world-cup-moments-catalog";
import { seedFromQuizDate } from "@/lib/quiz/rng";

const MANIFEST_DIR = join(process.cwd(), "data/quiz/lab-daily");

/** Preguntas 2 y 3 del quiz oficial diario: imagen + silueta. */
export const DAILY_LAB_QUESTION_FORMATS: readonly AutoGeneratedLabFormat[] = [
  "image_trivia",
  "guess_player_silhouette",
] as const;

export type QuizLabDailyPack = {
  quizDate: string;
  generatedAt: string;
  momentIds: string[];
  questions: LabQuestion[];
};

export type PregenerateQuizLabDailyPackResult = {
  quizDate: string;
  skipped: boolean;
  pack: QuizLabDailyPack | null;
};

function manifestPath(quizDate: string): string {
  return join(MANIFEST_DIR, `${quizDate}.json`);
}

function formatSeedForSlot(quizDate: string, slot: number): number {
  const base = seedFromQuizDate(quizDate);
  return base + slot * 9973;
}

function playerKeysFromMomentId(momentId: string | null | undefined): string[] {
  if (!momentId) return [];
  const moment = getWorldCupMomentsCatalog().moments.find((row) => row.id === momentId);
  if (!moment) return [];
  return moment.players.map(normalizePlayerKey);
}

export async function readQuizLabDailyPack(
  quizDate: string
): Promise<QuizLabDailyPack | null> {
  try {
    const raw = await readFile(manifestPath(quizDate), "utf8");
    return JSON.parse(raw) as QuizLabDailyPack;
  } catch {
    return null;
  }
}

export async function writeQuizLabDailyPack(pack: QuizLabDailyPack): Promise<void> {
  // En Vercel el filesystem del deploy es de solo lectura; el pack queda en memoria/BD.
  if (process.env.VERCEL === "1") return;

  try {
    await mkdir(MANIFEST_DIR, { recursive: true });
    await writeFile(manifestPath(pack.quizDate), JSON.stringify(pack, null, 2), "utf8");
  } catch (error) {
    console.warn(
      "[quiz/lab-daily] No se pudo escribir manifest en disco:",
      error instanceof Error ? error.message : error
    );
  }
}

export async function pregenerateQuizLabDailyPack(
  quizDate: string,
  options?: { force?: boolean }
): Promise<PregenerateQuizLabDailyPackResult> {
  if (!options?.force) {
    const existing = await readQuizLabDailyPack(quizDate);
    if (existing?.questions?.length) {
      return { quizDate, skipped: true, pack: existing };
    }
  }

  const excludeMomentIds: string[] = [];
  const excludePlayerKeys: string[] = [];
  const questions: LabQuestion[] = [];

  for (let slot = 0; slot < DAILY_LAB_QUESTION_FORMATS.length; slot++) {
    const format = DAILY_LAB_QUESTION_FORMATS[slot];
    const generated = await generateLabQuestion({
      format,
      questionId: `daily-${quizDate}-${format}`,
      seed: formatSeedForSlot(quizDate, slot),
      excludeMomentIds,
      excludePlayerKeys,
      minDifficulty: "medium",
      force: true,
    });

    if (!generated) continue;

    const materialized = await materializeLabQuestionAssets(generated, { force: true });
    questions.push(materialized);

    const momentId = "momentId" in materialized ? materialized.momentId : null;
    if (momentId) excludeMomentIds.push(momentId);
    for (const playerKey of playerKeysFromMomentId(momentId)) {
      if (!excludePlayerKeys.includes(playerKey)) {
        excludePlayerKeys.push(playerKey);
      }
    }
  }

  const pack: QuizLabDailyPack = {
    quizDate,
    generatedAt: new Date().toISOString(),
    momentIds: excludeMomentIds,
    questions,
  };

  await writeQuizLabDailyPack(pack);

  return { quizDate, skipped: false, pack };
}

/** Resumen ligero para `quizzes.settings_json`. */
export function labDailyPackSettingsSummary(pack: QuizLabDailyPack) {
  return {
    quiz_date: pack.quizDate,
    generated_at: pack.generatedAt,
    moment_ids: pack.momentIds,
    question_count: pack.questions.length,
    formats: pack.questions.map((q) => q.format),
  };
}
