import type { WorldCupMoment } from "@/lib/quiz/world-cup-moments";

type HardMomentSeed = Omit<
  WorldCupMoment,
  "status" | "source_url" | "source_label"
> & {
  source_label?: string;
};

function pending(seed: HardMomentSeed): WorldCupMoment {
  return {
    ...seed,
    source_url: null,
    source_label: seed.source_label ?? "Pendiente — autodiscover",
    status: "pending",
  };
}

/** Momentos media/alta dificultad: jugadores menos obvios, fases, rivales. */
export const HARD_WORLD_CUP_MOMENT_SEEDS: HardMomentSeed[] = [
  {
    id: "wc1970-carlos-alberto-goal",
    year: 1970,
    label: "Carlos Alberto — gol en la final vs Italia",
    moment_type: "goal",
    teams: ["Brasil", "Italia"],
    players: ["Carlos Alberto"],
    competition: "Final",
    difficulty: "medium",
    search_hint: "Carlos Alberto goal 1970 World Cup final Italy",
    local_path: "/images/quiz/historic/1970/wc1970-carlos-alberto-goal.jpg",
    image_alt: "Carlos Alberto marca en la final de 1970",
    quiz: {
      prompt: "¿Quién marcó este gol?",
      answer_type: "player",
      correct_option: "Carlos Alberto",
      options: ["Carlos Alberto", "Jairzinho", "Pelé", "Rivelino"],
      blur_start_px: 28,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc1970-jairzinho-goal",
    year: 1970,
    label: "Jairzinho — México 70",
    moment_type: "goal",
    teams: ["Brasil", "Inglaterra"],
    players: ["Jairzinho"],
    competition: "Cuartos",
    difficulty: "hard",
    search_hint: "Jairzinho goal World Cup 1970 quarter final",
    local_path: "/images/quiz/historic/1970/wc1970-jairzinho-goal.jpg",
    image_alt: "Jairzinho en el Mundial 1970",
    quiz: {
      prompt: "¿En qué fase del torneo fue esta jugada?",
      answer_type: "phase",
      correct_option: "Cuartos de final",
      options: ["Fase de grupos", "Octavos", "Cuartos de final", "Semifinal"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc1974-cruyff-penalty",
    year: 1974,
    label: "Cruyff — penalti arranque final 74",
    moment_type: "action",
    teams: ["Países Bajos", "Alemania"],
    players: ["Johan Cruyff"],
    competition: "Final",
    difficulty: "medium",
    search_hint: "Johan Cruyff penalty 1974 World Cup final",
    local_path: "/images/quiz/historic/1974/wc1974-cruyff-penalty.jpg",
    image_alt: "Cruyff en la final del Mundial 1974",
    quiz: {
      prompt: "¿Contra qué selección fue este partido?",
      answer_type: "opponent",
      correct_option: "Alemania",
      options: ["Alemania", "Brasil", "Argentina", "Italia"],
      blur_start_px: 28,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc1974-breitner-goal",
    year: 1974,
    label: "Paul Breitner — gol Alemania 74",
    moment_type: "goal",
    teams: ["Alemania", "Países Bajos"],
    players: ["Paul Breitner"],
    competition: "Final",
    difficulty: "hard",
    search_hint: "Paul Breitner goal 1974 World Cup final",
    local_path: "/images/quiz/historic/1974/wc1974-breitner-goal.jpg",
    image_alt: "Paul Breitner en la final de 1974",
    quiz: {
      prompt: "¿Quién marcó este gol?",
      answer_type: "player",
      correct_option: "Paul Breitner",
      options: ["Paul Breitner", "Gerd Müller", "Johan Neeskens", "Franz Beckenbauer"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc1978-kempes-celebration",
    year: 1978,
    label: "Mario Kempes — Argentina 78",
    moment_type: "celebration",
    teams: ["Argentina", "Países Bajos"],
    players: ["Mario Kempes"],
    competition: "Final",
    difficulty: "medium",
    search_hint: "Mario Kempes 1978 World Cup final celebration",
    local_path: "/images/quiz/historic/1978/wc1978-kempes-celebration.jpg",
    image_alt: "Mario Kempes en el Mundial 1978",
    quiz: {
      prompt: "¿Quién es el jugador?",
      answer_type: "player",
      correct_option: "Mario Kempes",
      options: ["Mario Kempes", "Daniel Passarella", "Leopoldo Luque", "Ricky Villa"],
      blur_start_px: 30,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc1982-schumacher-foul",
    year: 1982,
    label: "Schumacher — entrada a Battiston",
    moment_type: "iconic",
    teams: ["Alemania", "Francia"],
    players: ["Harald Schumacher", "Patrick Battiston"],
    competition: "Semifinal",
    difficulty: "hard",
    search_hint: "Schumacher Battiston 1982 World Cup semi final",
    local_path: "/images/quiz/historic/1982/wc1982-schumacher-foul.jpg",
    image_alt: "Schumacher y Battiston en semifinal 1982",
    quiz: {
      prompt: "¿En qué fase del torneo ocurrió?",
      answer_type: "phase",
      correct_option: "Semifinal",
      options: ["Octavos", "Cuartos de final", "Semifinal", "Final"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc1982-tardelli-goal",
    year: 1982,
    label: "Marco Tardelli — celebración final 82",
    moment_type: "celebration",
    teams: ["Italia", "Alemania"],
    players: ["Marco Tardelli"],
    competition: "Final",
    difficulty: "hard",
    search_hint: "Marco Tardelli goal celebration 1982 World Cup final",
    local_path: "/images/quiz/historic/1982/wc1982-tardelli-goal.jpg",
    image_alt: "Marco Tardelli celebra en la final de 1982",
    quiz: {
      prompt: "¿Quién marcó y celebra?",
      answer_type: "player",
      correct_option: "Marco Tardelli",
      options: ["Marco Tardelli", "Paolo Rossi", "Antonio Cabrini", "Gaetano Scirea"],
      blur_start_px: 34,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc1986-valdano-goal",
    year: 1986,
    label: "Jorge Valdano — México 86",
    moment_type: "goal",
    teams: ["Argentina", "Alemania"],
    players: ["Jorge Valdano"],
    competition: "Final",
    difficulty: "hard",
    search_hint: "Jorge Valdano goal 1986 World Cup final",
    local_path: "/images/quiz/historic/1986/wc1986-valdano-goal.jpg",
    image_alt: "Jorge Valdano en la final de 1986",
    quiz: {
      prompt: "¿Quién es el jugador?",
      answer_type: "player",
      correct_option: "Jorge Valdano",
      options: ["Jorge Valdano", "Jorge Burruchaga", "Claudio Caniggia", "Sergio Batista"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc1986-lineker-goal",
    year: 1986,
    label: "Gary Lineker — Inglaterra 86",
    moment_type: "goal",
    teams: ["Inglaterra", "Argentina"],
    players: ["Gary Lineker"],
    competition: "Cuartos",
    difficulty: "medium",
    search_hint: "Gary Lineker goal 1986 World Cup quarter final",
    local_path: "/images/quiz/historic/1986/wc1986-lineker-goal.jpg",
    image_alt: "Gary Lineker en el Mundial 1986",
    quiz: {
      prompt: "¿Contra qué selección marcó?",
      answer_type: "opponent",
      correct_option: "Argentina",
      options: ["Argentina", "Alemania", "Brasil", "Francia"],
      blur_start_px: 28,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc1990-schillaci-celebration",
    year: 1990,
    label: "Toto Schillaci — Italia 90",
    moment_type: "celebration",
    teams: ["Italia"],
    players: ["Salvatore Schillaci"],
    competition: "Semifinal",
    difficulty: "medium",
    search_hint: "Salvatore Schillaci 1990 World Cup celebration",
    local_path: "/images/quiz/historic/1990/wc1990-schillaci-celebration.jpg",
    image_alt: "Toto Schillaci en Italia 90",
    quiz: {
      prompt: "¿Quién es el jugador?",
      answer_type: "player",
      correct_option: "Salvatore Schillaci",
      options: ["Salvatore Schillaci", "Roberto Baggio", "Gianluca Vialli", "Paolo Maldini"],
      blur_start_px: 30,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc1990-caniggia-brazil",
    year: 1990,
    label: "Caniggia — gol vs Brasil",
    moment_type: "goal",
    teams: ["Argentina", "Brasil"],
    players: ["Claudio Caniggia"],
    competition: "Octavos",
    difficulty: "hard",
    search_hint: "Claudio Caniggia goal Brazil 1990 World Cup",
    local_path: "/images/quiz/historic/1990/wc1990-caniggia-brazil.jpg",
    image_alt: "Claudio Caniggia ante Brasil en 1990",
    quiz: {
      prompt: "¿Quién marcó este gol?",
      answer_type: "player",
      correct_option: "Claudio Caniggia",
      options: ["Claudio Caniggia", "Diego Maradona", "Gabriel Batistuta", "Pedro Troglio"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc1994-bebeto-celebration",
    year: 1994,
    label: "Bebeto — choncleta USA 94",
    moment_type: "celebration",
    teams: ["Brasil"],
    players: ["Bebeto"],
    competition: "Cuartos",
    difficulty: "medium",
    search_hint: "Bebeto cradle celebration 1994 World Cup",
    local_path: "/images/quiz/historic/1994/wc1994-bebeto-celebration.jpg",
    image_alt: "Bebeto celebra en el Mundial 1994",
    quiz: {
      prompt: "¿Quién celebra?",
      answer_type: "player",
      correct_option: "Bebeto",
      options: ["Bebeto", "Romário", "Rai", "Dunga"],
      blur_start_px: 28,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc1994-stoichkov-action",
    year: 1994,
    label: "Hristo Stoichkov — Bulgaria 94",
    moment_type: "action",
    teams: ["Bulgaria", "Alemania"],
    players: ["Hristo Stoichkov"],
    competition: "Cuartos",
    difficulty: "hard",
    search_hint: "Hristo Stoichkov 1994 World Cup quarter final",
    local_path: "/images/quiz/historic/1994/wc1994-stoichkov-action.jpg",
    image_alt: "Hristo Stoichkov en el Mundial 1994",
    quiz: {
      prompt: "¿Qué selección representa el jugador?",
      answer_type: "team",
      correct_option: "Bulgaria",
      options: ["Bulgaria", "Rumanía", "Croacia", "Rusia"],
      blur_start_px: 34,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc1998-thuram-celebration",
    year: 1998,
    label: "Lilian Thuram — semifinal vs Croacia",
    moment_type: "celebration",
    teams: ["Francia", "Croacia"],
    players: ["Lilian Thuram"],
    competition: "Semifinal",
    difficulty: "hard",
    search_hint: "Lilian Thuram goal celebration 1998 World Cup semi final Croatia",
    local_path: "/images/quiz/historic/1998/wc1998-thuram-celebration.jpg",
    image_alt: "Lilian Thuram celebra en 1998",
    quiz: {
      prompt: "¿Quién marcó? (pista: era defensa)",
      answer_type: "player",
      correct_option: "Lilian Thuram",
      options: ["Lilian Thuram", "Laurent Blanc", "Marcel Desailly", "Bixente Lizarazu"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc1998-bergkamp-argentina",
    year: 1998,
    label: "Dennis Bergkamp — control vs Argentina",
    moment_type: "action",
    teams: ["Países Bajos", "Argentina"],
    players: ["Dennis Bergkamp"],
    competition: "Cuartos",
    difficulty: "hard",
    search_hint: "Dennis Bergkamp 1998 World Cup quarter final Argentina",
    local_path: "/images/quiz/historic/1998/wc1998-bergkamp-argentina.jpg",
    image_alt: "Dennis Bergkamp ante Argentina en 1998",
    quiz: {
      prompt: "¿Contra qué selección fue este partido?",
      answer_type: "opponent",
      correct_option: "Argentina",
      options: ["Argentina", "Brasil", "Alemania", "Italia"],
      blur_start_px: 34,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc2002-ahn-italy-goal",
    year: 2002,
    label: "Ahn Jung-hwan — gol de oro vs Italia",
    moment_type: "goal",
    teams: ["Corea del Sur", "Italia"],
    players: ["Ahn Jung-hwan"],
    competition: "Octavos",
    difficulty: "hard",
    search_hint: "Ahn Jung-hwan golden goal Italy 2002 World Cup",
    local_path: "/images/quiz/historic/2002/wc2002-ahn-italy-goal.jpg",
    image_alt: "Ahn Jung-hwan celebra contra Italia en 2002",
    quiz: {
      prompt: "¿Quién marcó el gol de la eliminación?",
      answer_type: "player",
      correct_option: "Ahn Jung-hwan",
      options: ["Ahn Jung-hwan", "Park Ji-sung", "Lee Young-pyo", "Hong Myung-bo"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc2002-ronaldinho-freekick",
    year: 2002,
    label: "Ronaldinho — falta vs Inglaterra",
    moment_type: "goal",
    teams: ["Brasil", "Inglaterra"],
    players: ["Ronaldinho"],
    competition: "Cuartos",
    difficulty: "medium",
    search_hint: "Ronaldinho free kick England 2002 World Cup quarter final",
    local_path: "/images/quiz/historic/2002/wc2002-ronaldinho-freekick.jpg",
    image_alt: "Ronaldinho en el partido vs Inglaterra 2002",
    quiz: {
      prompt: "¿En qué fase fue este partido?",
      answer_type: "phase",
      correct_option: "Cuartos de final",
      options: ["Fase de grupos", "Octavos", "Cuartos de final", "Semifinal"],
      blur_start_px: 28,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc2006-grosso-penalty",
    year: 2006,
    label: "Fabio Grosso — penalti final 2006",
    moment_type: "goal",
    teams: ["Italia", "Francia"],
    players: ["Fabio Grosso"],
    competition: "Final",
    difficulty: "hard",
    search_hint: "Fabio Grosso penalty 2006 World Cup final",
    local_path: "/images/quiz/historic/2006/wc2006-grosso-penalty.jpg",
    image_alt: "Fabio Grosso en la tanda de 2006",
    quiz: {
      prompt: "¿Quién lanzó este penalti?",
      answer_type: "player",
      correct_option: "Fabio Grosso",
      options: ["Fabio Grosso", "Andrea Pirlo", "Daniele De Rossi", "Marco Materazzi"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc2006-klose-header",
    year: 2006,
    label: "Miroslav Klose — remate Alemania 2006",
    moment_type: "goal",
    teams: ["Alemania"],
    players: ["Miroslav Klose"],
    competition: "Cuartos",
    difficulty: "medium",
    search_hint: "Miroslav Klose header 2006 World Cup",
    local_path: "/images/quiz/historic/2006/wc2006-klose-header.jpg",
    image_alt: "Miroslav Klose en el Mundial 2006",
    quiz: {
      prompt: "¿Quién es el delantero?",
      answer_type: "player",
      correct_option: "Miroslav Klose",
      options: ["Miroslav Klose", "Lukas Podolski", "Bastian Schweinsteiger", "Michael Ballack"],
      blur_start_px: 30,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc2010-forlan-celebration",
    year: 2010,
    label: "Diego Forlán — Uruguay Sudáfrica",
    moment_type: "celebration",
    teams: ["Uruguay", "Países Bajos"],
    players: ["Diego Forlán"],
    competition: "Semifinal",
    difficulty: "medium",
    search_hint: "Diego Forlan 2010 World Cup semi final",
    local_path: "/images/quiz/historic/2010/wc2010-forlan-celebration.jpg",
    image_alt: "Diego Forlán en el Mundial 2010",
    quiz: {
      prompt: "¿Qué selección representa?",
      answer_type: "team",
      correct_option: "Uruguay",
      options: ["Uruguay", "Chile", "Paraguay", "Colombia"],
      blur_start_px: 28,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc2010-sneijder-action",
    year: 2010,
    label: "Wesley Sneijder — Holanda 2010",
    moment_type: "action",
    teams: ["Países Bajos", "Brasil"],
    players: ["Wesley Sneijder"],
    competition: "Cuartos",
    difficulty: "hard",
    search_hint: "Wesley Sneijder 2010 World Cup quarter final Brazil",
    local_path: "/images/quiz/historic/2010/wc2010-sneijder-action.jpg",
    image_alt: "Wesley Sneijder en Sudáfrica 2010",
    quiz: {
      prompt: "¿Quién es el jugador?",
      answer_type: "player",
      correct_option: "Wesley Sneijder",
      options: ["Wesley Sneijder", "Arjen Robben", "Robin van Persie", "Rafael van der Vaart"],
      blur_start_px: 34,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc2014-gotze-goal",
    year: 2014,
    label: "Mario Götze — gol decisivo final 2014",
    moment_type: "goal",
    teams: ["Alemania", "Argentina"],
    players: ["Mario Götze"],
    competition: "Final",
    difficulty: "medium",
    search_hint: "Mario Gotze goal 2014 World Cup final extra time",
    local_path: "/images/quiz/historic/2014/wc2014-gotze-goal.jpg",
    image_alt: "Mario Götze marca en la final de 2014",
    quiz: {
      prompt: "¿Quién marcó el gol de la final?",
      answer_type: "player",
      correct_option: "Mario Götze",
      options: ["Mario Götze", "Thomas Müller", "André Schürrle", "Miroslav Klose"],
      blur_start_px: 30,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc2014-cahill-volley",
    year: 2014,
    label: "Tim Cahill — volea vs Holanda",
    moment_type: "goal",
    teams: ["Australia", "Países Bajos"],
    players: ["Tim Cahill"],
    competition: "Octavos",
    difficulty: "hard",
    search_hint: "Tim Cahill volley Netherlands 2014 World Cup",
    local_path: "/images/quiz/historic/2014/wc2014-cahill-volley.jpg",
    image_alt: "Tim Cahill remata de volea en 2014",
    quiz: {
      prompt: "¿Quién marcó esta volea?",
      answer_type: "player",
      correct_option: "Tim Cahill",
      options: ["Tim Cahill", "Mile Jedinak", "Mark Bresciano", "Harry Kewell"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc2018-pavard-volley",
    year: 2018,
    label: "Benjamin Pavard — volea vs Argentina",
    moment_type: "goal",
    teams: ["Francia", "Argentina"],
    players: ["Benjamin Pavard"],
    competition: "Octavos",
    difficulty: "hard",
    search_hint: "Benjamin Pavard volley Argentina 2018 World Cup",
    local_path: "/images/quiz/historic/2018/wc2018-pavard-volley.jpg",
    image_alt: "Benjamin Pavard ante Argentina en 2018",
    quiz: {
      prompt: "¿Quién marcó este gol?",
      answer_type: "player",
      correct_option: "Benjamin Pavard",
      options: ["Benjamin Pavard", "Kylian Mbappé", "Antoine Griezmann", "Olivier Giroud"],
      blur_start_px: 34,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc2018-perisic-final",
    year: 2018,
    label: "Ivan Perisic — final 2018",
    moment_type: "goal",
    teams: ["Croacia", "Francia"],
    players: ["Ivan Perisic"],
    competition: "Final",
    difficulty: "hard",
    search_hint: "Ivan Perisic goal 2018 World Cup final France",
    local_path: "/images/quiz/historic/2018/wc2018-perisic-final.jpg",
    image_alt: "Ivan Perisic en la final de 2018",
    quiz: {
      prompt: "¿Quién marcó para Croacia?",
      answer_type: "player",
      correct_option: "Ivan Perisic",
      options: ["Ivan Perisic", "Mario Mandžukić", "Luka Modrić", "Ante Rebić"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc2022-dimaria-goal",
    year: 2022,
    label: "Ángel Di María — gol final 2022",
    moment_type: "goal",
    teams: ["Argentina", "Francia"],
    players: ["Ángel Di María"],
    competition: "Final",
    difficulty: "medium",
    search_hint: "Angel Di Maria goal 2022 World Cup final France",
    local_path: "/images/quiz/historic/2022/wc2022-dimaria-goal.jpg",
    image_alt: "Ángel Di María en la final de Qatar 2022",
    quiz: {
      prompt: "¿Quién marcó este gol?",
      answer_type: "player",
      correct_option: "Ángel Di María",
      options: ["Ángel Di María", "Lionel Messi", "Julián Álvarez", "Enzo Fernández"],
      blur_start_px: 30,
      reveal_seconds: 7,
    },
  },
  {
    id: "wc2022-martinez-save",
    year: 2022,
    label: "Emiliano Martínez — parada final 2022",
    moment_type: "save",
    teams: ["Argentina", "Francia"],
    players: ["Emiliano Martínez"],
    competition: "Final",
    difficulty: "hard",
    search_hint: "Emiliano Martinez save Kolo Muani 2022 World Cup final",
    local_path: "/images/quiz/historic/2022/wc2022-martinez-save.jpg",
    image_alt: "Emiliano Martínez para en la final de 2022",
    quiz: {
      prompt: "¿Quién es el portero?",
      answer_type: "player",
      correct_option: "Emiliano Martínez",
      options: ["Emiliano Martínez", "Hugo Lloris", "Thibaut Courtois", "Alisson Becker"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc2022-enzo-fernandez",
    year: 2022,
    label: "Enzo Fernández — Argentina 2022",
    moment_type: "action",
    teams: ["Argentina"],
    players: ["Enzo Fernández"],
    competition: "Fase de grupos",
    difficulty: "hard",
    search_hint: "Enzo Fernandez Argentina 2022 World Cup action",
    local_path: "/images/quiz/historic/2022/wc2022-enzo-fernandez.jpg",
    image_alt: "Enzo Fernández en el Mundial 2022",
    quiz: {
      prompt: "¿Quién es el jugador?",
      answer_type: "player",
      correct_option: "Enzo Fernández",
      options: ["Enzo Fernández", "Alexis Mac Allister", "Rodrigo De Paul", "Leandro Paredes"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc2006-lehmann-penalties",
    year: 2006,
    label: "Jens Lehmann — papelitos penaltis",
    moment_type: "iconic",
    teams: ["Alemania", "Argentina"],
    players: ["Jens Lehmann"],
    competition: "Cuartos",
    difficulty: "hard",
    search_hint: "Jens Lehmann penalty notes 2006 World Cup Argentina",
    local_path: "/images/quiz/historic/2006/wc2006-lehmann-penalties.jpg",
    image_alt: "Jens Lehmann en la tanda de 2006",
    quiz: {
      prompt: "¿Contra qué selección fue esta tanda?",
      answer_type: "opponent",
      correct_option: "Argentina",
      options: ["Argentina", "Italia", "España", "Brasil"],
      blur_start_px: 34,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc1998-barthez-save",
    year: 1998,
    label: "Fabien Barthez — parada Francia 98",
    moment_type: "save",
    teams: ["Francia", "Italia"],
    players: ["Fabien Barthez"],
    competition: "Cuartos",
    difficulty: "hard",
    search_hint: "Fabien Barthez save 1998 World Cup Italy quarter final",
    local_path: "/images/quiz/historic/1998/wc1998-barthez-save.jpg",
    image_alt: "Fabien Barthez en el Mundial 1998",
    quiz: {
      prompt: "¿Quién es el portero?",
      answer_type: "player",
      correct_option: "Fabien Barthez",
      options: ["Fabien Barthez", "Gianluigi Buffon", "Peter Schmeichel", "José Luis Chilavert"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
  {
    id: "wc2014-schurrle-assist",
    year: 2014,
    label: "André Schürrle — asistencia final 2014",
    moment_type: "action",
    teams: ["Alemania", "Argentina"],
    players: ["André Schürrle", "Mario Götze"],
    competition: "Final",
    difficulty: "hard",
    search_hint: "Andre Schurrle cross Gotze 2014 World Cup final",
    local_path: "/images/quiz/historic/2014/wc2014-schurrle-assist.jpg",
    image_alt: "André Schürrle en la jugada del gol de la final 2014",
    quiz: {
      prompt: "¿Quién dio la asistencia del gol?",
      answer_type: "player",
      correct_option: "André Schürrle",
      options: ["André Schürrle", "Thomas Müller", "Mesut Özil", "Toni Kroos"],
      blur_start_px: 36,
      reveal_seconds: 6,
    },
  },
];

export function hardMomentSeeds(): WorldCupMoment[] {
  return HARD_WORLD_CUP_MOMENT_SEEDS.map((seed) => pending(seed));
}
