import { canAccessQuizLab } from "@/lib/quiz/lab-access";
import { isAutoGeneratedLabFormat } from "@/lib/quiz/lab/auto-formats";
import { generateLabQuestion } from "@/lib/quiz/lab/generate-question.server";
import type { LabQuestionFormat } from "@/lib/quiz/lab/types";
import { createClient } from "@/lib/supabase/server";
import type { WorldCupMomentDifficulty } from "@/lib/quiz/world-cup-moments";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 120;

const ALLOWED_FORMATS = [
  "image_trivia",
  "guess_player_hair",
  "guess_player_eyes",
  "guess_player_silhouette",
] as const satisfies readonly LabQuestionFormat[];

type AllowedFormat = (typeof ALLOWED_FORMATS)[number];

function isAllowedFormat(value: string): value is AllowedFormat {
  return (ALLOWED_FORMATS as readonly string[]).includes(value);
}

async function assertLabAccess(): Promise<Response | null> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return Response.json({ error: "No autenticado." }, { status: 401 });
  }

  const { data: profile } = await supabase
    .from("profiles")
    .select("username")
    .eq("id", user.id)
    .maybeSingle();

  if (!canAccessQuizLab(profile?.username)) {
    return Response.json({ error: "Acceso denegado." }, { status: 403 });
  }

  return null;
}

export async function POST(request: Request) {
  const denied = await assertLabAccess();
  if (denied) return denied;

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: "JSON invalido." }, { status: 400 });
  }

  if (!body || typeof body !== "object") {
    return Response.json({ error: "Cuerpo invalido." }, { status: 400 });
  }

  const raw = body as Record<string, unknown>;
  const format = typeof raw.format === "string" ? raw.format : "";
  if (!isAllowedFormat(format) || !isAutoGeneratedLabFormat(format)) {
    return Response.json({ error: "Formato no soportado." }, { status: 400 });
  }

  const questionId =
    typeof raw.questionId === "string" && raw.questionId.trim()
      ? raw.questionId.trim()
      : undefined;
  const excludeMomentId =
    typeof raw.excludeMomentId === "string" && raw.excludeMomentId.trim()
      ? raw.excludeMomentId.trim()
      : null;
  const minDifficulty =
    raw.minDifficulty === "easy" ||
    raw.minDifficulty === "medium" ||
    raw.minDifficulty === "hard"
      ? (raw.minDifficulty as WorldCupMomentDifficulty)
      : "medium";
  const force = raw.force === true;

  try {
    const question = await generateLabQuestion({
      format,
      questionId,
      excludeMomentId,
      minDifficulty,
      force,
    });

    if (!question) {
      return Response.json(
        { error: "No hay momentos listos en el catalogo para este formato." },
        { status: 404 }
      );
    }

    return Response.json({ question });
  } catch (error) {
    console.error("[laboratorio/generate-question]", error);
    const detail =
      error instanceof Error ? error.message : "No se pudo generar la pregunta automaticamente.";
    return Response.json({ error: detail }, { status: 500 });
  }
}
